### ISSUE TITLE
Make the whole `GridItem`/`ListItem` a link

### ISSUE THREAD

**Issue by AlexMayol** [toniengelhardt/webapicheck#18]
Although the underline text on the title is a good hint, I'd find it better if the whole item was a `<NuxtLink>`. WDYT?

**Comment by toniengelhardt** [comment]
Yes, I was also thinking about it. The only reason why it is not like that atm is bc of the UX of clickable items on top of clickable items, aka. the info items that create popups. It might not be obvious that they open a popup and not the item if you hover, but that could be solved with some hover effects maybe.

I was also thinking about having detail pages for each API instead of only the links to MDN (see https://github.com/toniengelhardt/webapicheck/issues/4). This will probably improve SEO a lot.

**Comment by toniengelhardt** [comment]
No no, just the information on the card with explanations for the properties if there are any and the link to MDN. What would be really cool is to collect stats about the available APIs and bowser, OS, etc. whenever someone opens the page and then drop some charts. But that would require a backend...

**Comment by toniengelhardt** [comment]
If the events are annotated correctly it might actually be possible to use the [Plausible stats API](https://plausible.io/docs/stats-api) as a backend 🤔

**Comment by toniengelhardt** [comment]
It's implemented ✌🏽

**Comment by AlexMayol** [comment]
Wow that was fast, thank you!

**Comment by toniengelhardt** [comment]
No probs, it makes a lot of sense!
