### ISSUE TITLE
Scrollbar does not suit to the website.

### ISSUE THREAD

**Issue by thetejasmagade** [toniengelhardt/webapicheck#30]
Simple scrollbar is not suiting to the website. I think it will be a better if we can customize it. @toniengelhardt should I make a PR for same? 🙌🙌

![Screenshot 2023-03-21 114440](https://user-images.githubusercontent.com/53045273/226531941-6062b7c5-7c9e-4168-95c8-34dc94d6bcbf.jpg)

**Comment by toniengelhardt** [comment]
Ah yeah, that looks a bit stupid, which OS is this?

Would appreciate a PR!

On OS X the default scrollbar is actually kind of nice bc it auto-hides and doesn't take space:

![Screen-2023-03-21-101849](https://user-images.githubusercontent.com/2703233/226578188-597f029e-8259-4f48-91b8-736a2f62a3ba.gif)

If it is possible to style the scrollbar only on non-OSX devices it would be perfect:

<img width="371" alt="Screenshot 2023-03-21 at 10 29 43" src="https://user-images.githubusercontent.com/2703233/226580987-fe94423b-ecaf-43d5-88da-c9110990669b.png">

The horizontal ones should actually not be there at all, could maybe be fixed with `overflow-x: hidden` or smth.

FYI, for mobile I'm already hiding them completely, but I think that doesn't work on iOS either...

**Comment by toniengelhardt** [comment]
I'm not sure if that is good practice, I would rather keep it around. All big apps have scrollbars I think, at least on desktop.

**Comment by thetejasmagade** [comment]
@toniengelhardt PR Done ✅
